// utils/statsManager.js
const fs = require('fs');
const path = require('path');

const STATS_DIR = path.join(__dirname, '..', 'data');
const STATS_FILE = path.join(STATS_DIR, 'monthlyStats.json');

let stats = {
  month: '',
  users: {},
  voiceChannels: {}
};

const activeVoiceSessions = new Map(); // userId => {joinTime, channelId}

const swearWords = [
  'chuj',
  'chuja',
  'chujek',
  'chuju',
  'chujem',
  'chujnia',
  'chujowy',
  'chujowa',
  'chujowe',
  'cipa',
  'cipę',
  'cipe',
  'cipą',
  'cipie',
  'dojebać',
  'dojebac',
  'dojebie',
  'dojebał',
  'dojebal',
  'dojebała',
  'dojebala',
  'dojebałem',
  'dojebalem',
  'dojebałam',
  'dojebalam',
  'dojebię',
  'dopieprzać',
  'dopieprzac',
  'dopierdalać',
  'dopierdalac',
  'dopierdala',
  'dopierdalał',
  'dopierdalal',
  'dopierdalała',
  'dopierdalala',
  'dopierdoli',
  'dopierdolił',
  'dopierdolil',
  'dopierdolę',
  'dopierdole',
  'dopierdalający',
  'dopierdalajacy',
  'dopierdolić',
  'dopierdolic',
  'dupa',
  'dupie',
  'dupą',
  'dupcia',
  'dupeczka',
  'dupy',
  'dupe',
  'huj',
  'hujek',
  'hujnia',
  'huja',
  'huje',
  'hujem',
  'huju',
  'jebać',
  'jebac',
  'jebał',
  'jebal',
  'jebie',
  'jebią',
  'jebia',
  'jebak',
  'jebaka',
  'jebany',
  'jebane',
  'jebanka',
  'jebanko',
  'jebankiem',
  'jebanymi',
  'jebana',
  'jebanym',
  'jebanej',
  'jebaną',
  'jebani',
  'jebanych',
  'jebcie',
  'jebiący',
  'jebiacy',
  'jebiąca',
  'jebiaca',
  'jebiącego',
  'jebiacego',
  'jebiącej',
  'jebiacej',
  'jebię',
  'jebliwy',
  'jebnąć',
  'jebnac',
  'jebnąc',
  'jebnać',
  'jebnął',
  'jebnal',
  'jebną',
  'jebna',
  'jebnęła',
  'jebnela',
  'jebnie',
  'jebnij',
  'jebut',
  'koorwa',
  'kórwa',
  'kurestwo',
  'kurew',
  'kurewski',
  'kurewska',
  'kurewskiej',
  'kurewską',
  'kurewsko',
  'kurewstwo',
  'kurwa',
  'kurwaa',
  'kurwami',
  'kurwą',
  'kurwe',
  'kurwę',
  'kurwie',
  'kurwiska',
  'kurwo',
  'kurwy',
  'kurwach',
  'kurwiarz',
  'kurwiący',
  'kurwica',
  'kurwić',
  'kurwic',
  'kurwidołek',
  'kurwik',
  'kurwiki',
  'kurwiszcze',
  'kurwiszon',
  'kurwiszona',
  'kurwiszonem',
  'kurwiszony',
  'kutas',
  'kutasa',
  'kutasie',
  'kutasem',
  'kutasy',
  'kutasów',
  'kutasow',
  'kutasach',
  'kutasami',
  'matkojebca',
  'matkojebcy',
  'matkojebcą',
  'matkojebcami',
  'matkojebcach',
  'nabarłożyć',
  'najebać',
  'najebac',
  'najebał',
  'najebal',
  'najebała',
  'najebala',
  'najebane',
  'najebany',
  'najebaną',
  'najebana',
  'najebie',
  'najebią',
  'najebia',
  'naopierdalać',
  'naopierdalac',
  'naopierdalał',
  'naopierdalal',
  'naopierdalała',
  'naopierdalala',
  'napierdalać',
  'napierdalac',
  'napierdalający',
  'napierdalajacy',
  'napierdolić',
  'napierdolic',
  'nawpierdalać',
  'nawpierdalac',
  'nawpierdalał',
  'nawpierdalal',
  'nawpierdalała',
  'nawpierdalala',
  'obsrywać',
  'obsrywac',
  'obsrywający',
  'obsrywajacy',
  'odpieprzać',
  'odpieprzac',
  'odpieprzy',
  'odpieprzył',
  'odpieprzyl',
  'odpieprzyła',
  'odpieprzyla',
  'odpierdalać',
  'odpierdalac',
  'odpierdol',
  'odpierdolił',
  'odpierdolil',
  'odpierdoliła',
  'odpierdolila',
  'odpierdoli',
  'odpierdalający',
  'odpierdalajacy',
  'odpierdalająca',
  'odpierdalajaca',
  'odpierdolić',
  'odpierdolic',
  'opieprzający',
  'opierdalać',
  'opierdalac',
  'opierdala',
  'opierdalający',
  'opierdalajacy',
  'opierdol',
  'opierdolić',
  'opierdolic',
  'opierdoli',
  'opierdolą',
  'opierdola',
  'piczka',
  'pieprznięty',
  'pieprzniety',
  'pieprzony',
  'pierdel',
  'pierdlu',
  'pierdolą',
  'pierdola',
  'pierdolący',
  'pierdolacy',
  'pierdoląca',
  'pierdolaca',
  'pierdol',
  'pierdole',
  'pierdolenie',
  'pierdoleniem',
  'pierdoleniu',
  'pierdolę',
  'pierdolec',
  'pierdolić',
  'pierdolicie',
  'pierdolic',
  'pierdolił',
  'pierdolil',
  'pierdoliła',
  'pierdolila',
  'pierdoli',
  'pierdolnięty',
  'pierdolniety',
  'pierdolisz',
  'pierdolnąć',
  'pierdolnac',
  'pierdolnął',
  'pierdolnal',
  'pierdolnęła',
  'pierdolnela',
  'pierdolnie',
  'pierdolnij',
  'pierdolnik',
  'pierdolona',
  'pierdolone',
  'pierdolony',
  'pierdołki',
  'pierdzący',
  'pierdzieć',
  'pierdziec',
  'pizda',
  'pizdą',
  'pizde',
  'pizdę',
  'piździe',
  'pizdzie',
  'pizdnąć',
  'pizdnac',
  'pizdu',
  'podpierdalać',
  'podpierdalac',
  'podpierdala',
  'podpierdalający',
  'podpierdalajacy',
  'podpierdolić',
  'podpierdolic',
  'podpierdoli',
  'pojeb',
  'pojeba',
  'pojebami',
  'pojebani',
  'pojebanego',
  'pojebanemu',
  'pojebany',
  'pojebanych',
  'pojebanym',
  'pojebanymi',
  'pojebem',
  'pojebać',
  'pojebac',
  'pojebalo',
  'popierdala',
  'popierdalac',
  'popierdalać',
  'popierdolić',
  'popierdolic',
  'popierdoli',
  'popierdolonego',
  'popierdolonemu',
  'popierdolonym',
  'popierdolone',
  'popierdoleni',
  'popierdolony',
  'porozpierdalać',
  'porozpierdala',
  'porozpierdalac',
  'poruchac',
  'poruchać',
  'przejebać',
  'przejebane',
  'przejebac',
  'przyjebali',
  'przepierdalać',
  'przepierdalac',
  'przepierdala',
  'przepierdalający',
  'przepierdalajacy',
  'przepierdalająca',
  'przepierdalajaca',
  'przepierdolić',
  'przepierdolic',
  'przyjebać',
  'przyjebac',
  'przyjebie',
  'przyjebała',
  'przyjebala',
  'przyjebał',
  'przyjebal',
  'przypieprzać',
  'przypieprzac',
  'przypieprzający',
  'przypieprzajacy',
  'przypieprzająca',
  'przypieprzajaca',
  'przypierdalać',
  'przypierdalac',
  'przypierdala',
  'przypierdoli',
  'przypierdalający',
  'przypierdalajacy',
  'przypierdolić',
  'przypierdolic',
  'qrwa',
  'rozjebać',
  'rozjebac',
  'rozjebie',
  'rozjebała',
  'rozjebią',
  'rozpierdalać',
  'rozpierdalac',
  'rozpierdala',
  'rozpierdolić',
  'rozpierdolic',
  'rozpierdole',
  'rozpierdoli',
  'rozpierducha',
  'skurwić',
  'skurwiel',
  'skurwiela',
  'skurwielem',
  'skurwielu',
  'skurwysyn',
  'skurwysynów',
  'skurwysynow',
  'skurwysyna',
  'skurwysynem',
  'skurwysynu',
  'skurwysyny',
  'skurwysyński',
  'skurwysynski',
  'skurwysyństwo',
  'skurwysynstwo',
  'spieprzać',
  'spieprzac',
  'spieprza',
  'spieprzaj',
  'spieprzajcie',
  'spieprzają',
  'spieprzaja',
  'spieprzający',
  'spieprzajacy',
  'spieprzająca',
  'spieprzajaca',
  'spierdalać',
  'spierdalac',
  'spierdala',
  'spierdalał',
  'spierdalała',
  'spierdalal',
  'spierdalalcie',
  'spierdalala',
  'spierdalający',
  'spierdalajacy',
  'spierdolić',
  'spierdolic',
  'spierdoli',
  'spierdoliła',
  'spierdoliło',
  'spierdolą',
  'spierdola',
  'srać',
  'srac',
  'srający',
  'srajacy',
  'srając',
  'srajac',
  'sraj',
  'sukinsyn',
  'sukinsyny',
  'sukinsynom',
  'sukinsynowi',
  'sukinsynów',
  'sukinsynow',
  'śmierdziel',
  'udupić',
  'ujebać',
  'ujebac',
  'ujebał',
  'ujebal',
  'ujebana',
  'ujebany',
  'ujebie',
  'ujebała',
  'ujebala',
  'upierdalać',
  'upierdalac',
  'upierdala',
  'upierdoli',
  'upierdolić',
  'upierdolic',
  'upierdolą',
  'upierdola',
  'upierdoleni',
  'wjebać',
  'wjebac',
  'wjebie',
  'wjebią',
  'wjebia',
  'wjebiemy',
  'wjebiecie',
  'wkurwiać',
  'wkurwiac',
  'wkurwi',
  'wkurwia',
  'wkurwiał',
  'wkurwial',
  'wkurwiający',
  'wkurwiajacy',
  'wkurwiająca',
  'wkurwiajaca',
  'wkurwić',
  'wkurwic',
  'wkurwiacie',
  'wkurwiają',
  'wkurwiali',
  'wkurwią',
  'wkurwimy',
  'wkurwicite',
  'wpierdalać',
  'wpierdalac',
  'wpierdalający',
  'wpierdalajacy',
  'wpierdol',
  'wpierdolić',
  'wpierdolic',
  'wpizdu',
  'wyjebać',
  'wyjebac',
  'wyjebali',
  'wyjebał',
  'wyjebała',
  'wyjebały',
  'wyjebie',
  'wyjebią',
  'wyjebia',
  'wyjebiesz',
  'wyjebiecie',
  'wyjebiemy',
  'wypieprzać',
  'wypieprzac',
  'wypieprza',
  'wypieprzał',
  'wypieprzal',
  'wypieprzała',
  'wypieprzala',
  'wypieprzy',
  'wypieprzyła',
  'wypieprzyla',
  'wypieprzył',
  'wypieprzyl',
  'wypierdal',
  'wypierdalać',
  'wypierdalac',
  'wypierdala',
  'wypierdalaj',
  'wypierdalał',
  'wypierdalal',
  'wypierdalała',
  'wypierdalala',
  'wypierdolić',
  'wypierdolic',
  'wypierdoli',
  'wypierdolimy',
  'wypierdolicie',
  'wypierdolą',
  'wypierdola',
  'wypierdolili',
  'wypierdolił',
  'wypierdolil',
  'wypierdoliła',
  'wypierdolila',
  'zajebać',
  'zajebac',
  'zajebie',
  'zajebią',
  'zajebia',
  'zajebiał',
  'zajebial',
  'zajebała',
  'zajebiala',
  'zajebali',
  'zajebana',
  'zajebani',
  'zajebane',
  'zajebany',
  'zajebanych',
  'zajebanym',
  'zajebanymi',
  'zajebiste',
  'zajebisty',
  'zajebistych',
  'zajebista',
  'zajebistym',
  'zajebistymi',
  'zajebiście',
  'zajebiscie',
  'zapieprzyć',
  'zapieprzyc',
  'zapieprzy',
  'zapieprzył',
  'zapieprzyl',
  'zapieprzyła',
  'zapieprzyla',
  'zapieprzą',
  'zapieprza',
  'zapieprzymy',
  'zapieprzycie',
  'zapieprzysz',
  'zapierdala',
  'zapierdalać',
  'zapierdalac',
  'zapierdalaja',
  'zapierdalał',
  'zapierdalaj',
  'zapierdalajcie',
  'zapierdalała',
  'zapierdalala',
  'zapierdalali',
  'zapierdalający',
  'zapierdalajacy',
  'zapierdolić',
  'zapierdolic',
  'zapierdoli',
  'zapierdolił',
  'zapierdolil',
  'zapierdoliła',
  'zapierdolila',
  'zapierdolą',
  'zapierdola',
  'zapierniczać',
  'zapierniczający',
  'zasrać',
  'zasranym',
  'zasrywać',
  'zasrywający',
  'zesrywać',
  'zesrywający',
  'zjebać',
  'zjebac',
  'zjebał',
  'zjebal',
  'zjebała',
  'zjebala',
  'zjebana',
  'zjebią',
  'zjebali',
  'zjeby',

  // Uzupełnienia – mocne wulgaryzmy
  'chuje',
  'chujów',
  'chujow',
  'chujami',
  'chujach',
  'chujom',
  'pizdy',
  'pizdo',
  'pizdom',
  'pizdami',
  'pizdach',
  'pizd',
  'cipy',
  'cipo',
  'cipom',
  'cipami',
  'cipach',
  'cipkami',
  'odjebać',
  'odjebac',
  'odjebie',
  'odjebał',
  'odjebal',
  'odjebała',
  'odjebala',
  'odjebałem',
  'odjebalem',
  'odjebałam',
  'odjebalam',
  'odjebany',
  'odjebana',
  'odjebane',
  'odjebani',
  'odjebanych',
  'odjebanym',
  'odjebanymi',
  'ruchać',
  'ruchac',
  'rucha',
  'rucham',
  'ruchasz',
  'ruchają',
  'ruchaja',
  'ruchaj',
  'ruchajcie',
  'ruchany',
  'ruchana',
  'ruchane',
  'poruchał',
  'poruchal',
  'poruchana',
  'spierdalaj',
  'wypierdalaj',
  'zapierdalaj',
  'odpierdalaj',
  'napierdalaj',
  'jebaj',
  'fiut',
  'fiuta',
  'fiutem',
  'fiucie',
  'fiuty',
  'fiutów',
  'fiutow',
  'fiutami',
  'cwel',
  'cwela',
  'cwelem',
  'cwelu',
  'cwele',
  'cweli',
  'szmata',
  'szmaty',
  'szmato',
  'szmatą',
  'szmatę',
  'szmatami',
  'bladź',
  'bladzi',
  'bladzia',
  'kurwiarza',
  'kurwiarzem',
  'kurwiarzu',
  'kurwiarze',
  'kurewka',
  'kurewki',
  'kurewką',
  'kurewkę',
  'skurwiały',
  'skurwiala',
  'skurwiale',
  'skurwialy',
  'skurwysynek',
  'skurwysynka',
  'skurwysynkiem',
  'chujostwo',
  'chujowizna',
  'chujowo',
  'chujowość',
  'chujowych',
  'odpierdol się',
  'odpierdol sie',
  'jebaj się',
  'jebaj sie',
  'hwdp',
  'chwdp',
  'hw dp'
];


function ensureDir() {
  if (!fs.existsSync(STATS_DIR)) fs.mkdirSync(STATS_DIR, { recursive: true });
}

function loadStats() {
  ensureDir();
  if (fs.existsSync(STATS_FILE)) {
    try {
      stats = JSON.parse(fs.readFileSync(STATS_FILE, 'utf8'));
    } catch (e) { console.error('Błąd wczytywania stats:', e); }
  }
  if (!stats.month) stats.month = getCurrentMonth();
  return stats;
}

function saveStats() {
  ensureDir();
  try { fs.writeFileSync(STATS_FILE, JSON.stringify(stats, null, 2)); } 
  catch (e) { console.error('Błąd zapisu stats:', e); }
}

function getCurrentMonth() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

function getOrCreateUser(userId) {
  if (!stats.users[userId]) {
    stats.users[userId] = { messages: 0, voiceTime: 0, emojis: 0, swears: 0 };
  }
  return stats.users[userId];
}

function incrementUserStat(userId, key, amount = 1) {
  const user = getOrCreateUser(userId);
  user[key] += amount;
  saveStats();
}

function joinVoice(userId, channelId) {
  if (!userId || !channelId) return;
  activeVoiceSessions.set(userId, { joinTime: Date.now(), channelId });
  console.log(`🔊 [VOICE] ${userId} dołączył do kanału ${channelId}`);
}

function leaveVoice(userId) {
  const session = activeVoiceSessions.get(userId);
  if (!session) return;
  
  const timeSpent = Math.floor((Date.now() - session.joinTime) / 1000);
  activeVoiceSessions.delete(userId);
  
  if (timeSpent < 30) {
    console.log(`⏭️ [VOICE] ${userId} spędził za mało czasu (${timeSpent}s) – pominięto`);
    return;
  }

  const user = getOrCreateUser(userId);
  user.voiceTime += timeSpent;
  
  if (!stats.voiceChannels[session.channelId]) stats.voiceChannels[session.channelId] = 0;
  stats.voiceChannels[session.channelId] += timeSpent;

  saveStats();
  console.log(`✅ [VOICE] ${userId} spędził ${timeSpent}s na kanale ${session.channelId}`);
}

async function initializeVoiceSessions(client) {
  console.log('🔄 Inicjalizacja sesji głosowych (osoby już na VC)...');
  let count = 0;
  for (const guild of client.guilds.cache.values()) {
    for (const [memberId, member] of guild.members.cache) {
      if (member.voice.channelId) {
        joinVoice(memberId, member.voice.channelId);
        count++;
      }
    }
  }
  console.log(`✅ Zainicjalizowano ${count} aktywnych sesji głosowych`);
}

async function checkMonthlyReset(client) {
  const currentMonth = getCurrentMonth();
  if (currentMonth !== stats.month && stats.month) {
    console.log(`🔄 Nowy miesiąc! Wysyłam podsumowanie za ${stats.month}`);
    await sendMonthlySummary(client, { ...stats });
    stats = { month: currentMonth, users: {}, voiceChannels: {} };
    saveStats();
  }
}

async function sendMonthlySummary(client, oldStats) { /* bez zmian – zostawiam jak było */ 
  // (cała funkcja sendMonthlySummary pozostaje taka sama jak wcześniej)
  try {
    const channel = await client.channels.fetch('1083113537293008988').catch(() => null);
    if (!channel) return console.error('❌ Nie znaleziono kanału #czat');

    const usersArray = Object.entries(oldStats.users)
      .map(([userId, data]) => ({ userId, ...data }))
      .filter(u => u.messages > 0 || u.voiceTime > 0);

    const topMessages = [...usersArray].sort((a,b) => b.messages - a.messages).slice(0,10);
    const topVoice = [...usersArray].sort((a,b) => b.voiceTime - a.voiceTime).slice(0,10);
    const topEmojis = usersArray.sort((a,b) => b.emojis - a.emojis)[0];
    const topSwears = usersArray.sort((a,b) => b.swears - a.swears)[0];

    let topVC = { name: 'Brak danych', time: 0 };
    if (Object.keys(oldStats.voiceChannels).length) {
      const [chId, sec] = Object.entries(oldStats.voiceChannels).sort((a,b) => b[1]-a[1])[0];
      const vc = await client.channels.fetch(chId).catch(() => null);
      topVC = { name: vc?.name || chId, time: sec };
    }

    const formatTime = s => {
      const h = Math.floor(s / 3600);
      const m = Math.floor((s % 3600) / 60);
      return h ? `${h}g ${m}m` : `${m}m`;
    };

    const embed = {
      color: 0x0099ff,
      title: `📊 Podsumowanie miesiąca ${oldStats.month}`,
      description: 'Ranking aktywności serwera',
      fields: [
        { name: '🏆 Top 10 Wiadomości', value: topMessages.map((u,i) => `${i+1}. <@${u.userId}> — **${u.messages}** msg`).join('\n') || '—', inline: true },
        { name: '🎤 Top 10 Czasu na VC', value: topVoice.map((u,i) => `${i+1}. <@${u.userId}> — **${formatTime(u.voiceTime)}**`).join('\n') || '—', inline: true },
        { name: '😀 Najwięcej emotek', value: topEmojis ? `<@${topEmojis.userId}> — **${topEmojis.emojis}**` : '—', inline: false },
        { name: '🤬 Najwięcej przekleństw', value: topSwears ? `<@${topSwears.userId}> — **${topSwears.swears}**` : '—', inline: false },
        { name: '🔊 Najaktywniejszy kanał głosowy', value: `**${topVC.name}** — **${formatTime(topVC.time)}**`, inline: false }
      ],
      timestamp: new Date()
    };

    await channel.send({ embeds: [embed] });
    console.log('✅ Podsumowanie miesięczne wysłane na #czat');
  } catch (err) {
    console.error('Błąd wysyłania podsumowania:', err);
  }
}

module.exports = {
  loadStats,
  incrementUserStat,
  joinVoice,
  leaveVoice,
  initializeVoiceSessions,
  checkMonthlyReset,
  swearWords
};